services:
  mongo:
    image: mongo:7
    container_name: task_tracker_mongo
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-tasktracker}
    command: mongod --auth --bind_ip_all
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT:-27018}:27017"

  backend:
    build:
      context: ./backend
    container_name: task_tracker_backend
    restart: always
    env_file:
      - ./.env
    environment:
      MONGO_URI: mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD}@mongo:27017/${MONGO_DATABASE:-tasktracker}?authSource=admin
      PORT: ${PORT:-8000}
      AUTHTOKEN_SECRETKEY: ${AUTHTOKEN_SECRETKEY}
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    depends_on:
      - mongo

volumes:
  mongo_data:
